server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service #规则ID
          uri: lb://userservice # 负载均衡对应的服务名称，一定要保持一直
          predicates: # 断言
            - Path=/user/** # 针对所有访问/user/**的服务都做整个规则处理
            - Before=2025-01-20T17:42:47.789-07:00[America/Denver]
        #          filters:
        #            - AddRequestHeader=Truth, Handsome
        - id: order-service #规则ID
          uri: lb://orderservice # 负载均衡对应的服务名称，一定要保持一直
          predicates: # 断言
            - Path=/order/** # 针对所有访问/user/**的服务都做整个规则处理
      default-filters:
        - AddRequestHeader=Truth, Handsome
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://127.0.0.1:5500"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期